"""add roles column

Revision ID: c80985d81686
Revises: 04457c3b1d44
Create Date: 2023-06-20 15:12:13.533706

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c80985d81686"
down_revision = "04457c3b1d44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("roles", sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
