"""hashed_password->password

Revision ID: ffd45b10cb7d
Revises: c80985d81686
Create Date: 2023-06-20 17:19:44.784858

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ffd45b10cb7d"
down_revision = "c80985d81686"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.create_unique_constraint(None, "users", ["id"])
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("users", "password")
    # ### end Alembic commands ###
